[package]
name = "hentai-downloader"
version = "0.2.0"
authors = ["rnic <mathan0203@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
reqwest = { version = "0.11", features = ["blocking"] }
url = "2.5.8"
select = "0.6"
threadpool = "1.7.1"
